version: 2
orbs:
  node: circleci/node@0.0.7

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - run:
        name: Install dependencies
        command: npm install
      - run:
        name: Test
        command: npm run test:unit

workflows:
  version: 2
  build:
    jobs:
      - test
