version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: git config --global user.email $email
      - run: git config --global user.name $name
      - run: npm install
      - run: ./deploy.sh
